type: http
name: List loan applications
url: '{{baseUrl}}/applications?status=denied&productType=auto_loan&limit=25&offset=0'
method: GET
headers:
  - key: Accept
    value: application/json
queryParams:
  - key: status
    value: denied
    description: Filter by application status
  - key: productType
    value: auto_loan
    description: Filter by loan product type
  - key: limit
    value: '25'
  - key: offset
    value: '0'
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "data": [
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 5944.245609499843,
                "termMonths": 4711,
                "status": "approved",
                "createdAt": "1981-06-22T23:04:38.326Z",
                "updatedAt": "1970-01-23T14:39:06.548Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "completed",
                  "decision": "referred_to_manual",
                  "riskScore": 59,
                  "evaluatedAt": "1985-04-10T13:31:49.453Z"
                }
              },
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 1786.8759519097255,
                "termMonths": 9915,
                "status": "denied",
                "createdAt": "1969-01-28T07:52:22.743Z",
                "updatedAt": "1972-05-26T05:56:40.761Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "failed",
                  "decision": "denied",
                  "riskScore": 79,
                  "evaluatedAt": "1972-03-14T04:45:10.827Z"
                }
              }
            ],
            "total": 5291,
            "limit": 7190,
            "offset": 1339
          }
      headers:
        - key: Content-Type
          value: application/json
    name: List of applications
